// This file is auto-generated by Lovable. Do not modify it.

import { createLovableAuth } from "@lovable.dev/cloud-auth-js";
import { supabase } from "../supabase/client";
const lovableAuth = createLovableAuth();

type SignInOptions = {
  redirect_uri?: string;
  extraParams?: Record<string, string>;
};

type LovableAuthTokens = {
  access_token: string;
  refresh_token: string;
};

function isLovableAuthTokens(value: unknown): value is LovableAuthTokens {
  return (
    typeof value === 'object' &&
    value !== null &&
    typeof (value as any).access_token === 'string' &&
    typeof (value as any).refresh_token === 'string'
  );
}

export const lovable = {
  auth: {
    signInWithOAuth: async (provider: "google" | "apple" | "microsoft" | "lovable", opts?: SignInOptions) => {
      const result = await lovableAuth.signInWithOAuth(provider, {
        redirect_uri: opts?.redirect_uri,
        extraParams: {
          ...opts?.extraParams,
        },
      });

      if (result.redirected) {
        return result;
      }

      if (result.error) {
        return result;
      }

      const tokens = result.tokens;
      if (!isLovableAuthTokens(tokens)) {
        return { error: new Error('Invalid auth tokens returned from Lovable.') };
      }

      try {
        await supabase.auth.setSession(tokens);
      } catch (e) {
        return { error: e instanceof Error ? e : new Error(String(e)) };
      }
      return result;
    },
  },
};
